In [ ]:
#Numpy="Numerical Python "

In [1]:
import numpy as np


In [3]:
w=14,15,48,79,70,41
h=12,17,1,48,45,46

In [13]:
print('the height is',h,type(h))
print('the weight is',w,type(w))

the height is (12, 17, 1, 48, 45, 46) <class 'tuple'>
the weight is (14, 15, 48, 79, 70, 41) <class 'tuple'>


In [15]:
w_n=np.array(w) #converting a normal string to numpy string 
w_n

array([14, 15, 48, 79, 70, 41])

In [16]:
type(w_n)

numpy.ndarray

In [18]:
h_n=np.array(h)
h_n

array([12, 17,  1, 48, 45, 46])

In [19]:
np.array([12,10,14,14])*2   #without numpy we cannot multiply the list simply 

array([24, 20, 28, 28])

In [20]:
m=[123,147,15,12,'raghu','mj','lalala']

In [22]:
m[-2][1]

'j'

In [23]:
m=np.array(m)

In [24]:
m

array(['123', '147', '15', '12', 'raghu', 'mj', 'lalala'], dtype='<U11')

In [25]:
m[:-1] #it starts from behind as (-ve) and if postive it will start from beginning and witrh indexing starting from 0 

array(['123', '147', '15', '12', 'raghu', 'mj'], dtype='<U11')

In [29]:
a=[54,13,68,654321,654,7,156]
a=np.array(a)
a>100 #providing values which are greater than 100 

array([False, False, False,  True,  True, False,  True])

In [32]:
a[a>=100] #values which are greater then 100

array([654321,    654,    156])

In [4]:
raghu=np.array(([9,1,4,5],[7,5,4,3],[1,4,7,9]))
raghu #n-dimensional array in numpy

array([[9, 1, 4, 5],
       [7, 5, 4, 3],
       [1, 4, 7, 9]])

In [40]:
raghu.shape

(3, 4)

In [6]:
raghu[0] #only the first row

array([9, 1, 4, 5])

In [7]:
raghu[0:2] #only the first and second column

array([[9, 1, 4, 5],
       [7, 5, 4, 3]])

In [8]:
raghu[0:2,-1] 

array([5, 3])

In [10]:
raghu[0:3,0:2]

array([[9, 1],
       [7, 5],
       [1, 4]])

In [13]:
raghu[0][0]=10 #replacing the number at a certain place as per the wish 
raghu

array([[10,  1,  4,  5],
       [ 7,  5,  4,  3],
       [ 1,  4,  7,  9]])

In [16]:
raghu=np.zeros((3,1))
raghu #filling with zeros

array([[0.],
       [0.],
       [0.]])

In [21]:
np.full((2,3),23)

array([[23, 23, 23],
       [23, 23, 23]])

In [25]:
print(np.array([raghu[0,0],raghu[0,0],raghu[1,0]]))

[0. 0. 0.]


In [27]:
list(range(1,10)) #giving values form 1 upto 10 but not including 10

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(4) #if nothing is provided it will start from 0

array([0, 1, 2, 3])

In [3]:
a=np.array(([1,2,3],[4,5,7],[78,15,14]))
a

array([[ 1,  2,  3],
       [ 4,  5,  7],
       [78, 15, 14]])

In [4]:
b=np.array([0,2,0,1])
b

array([0, 2, 0, 1])

In [10]:
print(a[b,b])

[ 1 14  1  5]


In [4]:
x=np.array([10,14,15])
y=np.array([19,14,13])
print(x)
print(y)

[10 14 15]
[19 14 13]


In [5]:
x+y

array([29, 28, 28])

In [6]:
x-y

array([-9,  0,  2])

In [7]:
x*y

array([190, 196, 195])

In [8]:
x/y

array([0.52631579, 1.        , 1.15384615])

In [10]:
np.sqrt(x)

array([3.16227766, 3.74165739, 3.87298335])

In [11]:
np.dot(x,y) #vector product 

581

In [14]:
np.sum(x,axis=0) #sum of values of the array 

39

In [18]:
o=np.array(([20,14],[23,154]))
o

array([[ 20,  14],
       [ 23, 154]])

In [20]:
o.T #transpose of the array 

array([[ 20,  23],
       [ 14, 154]])

In [22]:
c=np.array([[14,15,17],[48,46,15],[89,65,7]])
d=np.array([1,2,1])

In [23]:
y=c+d #addition of the two arrays with different dimensions, as per mathematical concept
print(y)

[[15 17 18]
 [49 48 16]
 [90 67  8]]
